### ISSUE TITLE
Update to latest hock

### ISSUE THREAD

**Issue by robertkowalski** [npm/npm-registry-mock#28]
Use the latest hock version

Hock will not create a http-server on it's own in the newest version and let the user create the server. This is nice as it enables us to run tests on https.

Example from the hock readme:

``` js
    var http = require('http'),
        hock = require('hock'),
        request = require('request');

    var mock = hock.createHock();
    mock
        .get('/some/url')
        .reply(200, 'Hello!');

    var server = http.createServer(mock.handler);
    server.listen(1337, function () {
        request('http://localhost:' + 1337 + '/some/url', function(err, res, body) {
           console.log(body);
        });
    });
```

Proposal:
- the default server should be still created (in npm-registry-mock)
- if you pass in an option `useOwnServer: true` npm registry mock will just return the hock middleware which you can then pass into your own server (e.g. a server using https)

**Comment by robertkowalski** [comment]
@iarna @othiym23 would that help for your tests now or in the future?

**Comment by othiym23** [comment]
At some point, I want to be able to test things like SSL connections, as well as create tests around proxying, tunneling agents, and other scenarios that frequently cause problems for enterprise users, but that are difficult to test with traditional integration tests. Because you frequently need some control over the whole environment, I've been thinking that it might make sense to use some form of virtualization or containerization for those tests, especially because eventually I want to have those tests included in CI (and also to be able to run them on Windows, where many users have difficulty, and where it's hard to verify bug fixes).

It's conceivable that this could be a part of that, but in that case I think the most useful thing would actually be to run a mock registry as a child process, sort of like what @isaacs has been doing with https://github.com/npm/how-to-npm's built-in registry server. However, this seems like it could be a useful interim step.

The interface I prefer is just a `server` option that allows you to pass in an instance of `{http,https}.Server`, instead of anything more complicated. You can add the listeners via `server.on('request', handler)`, and if we want to get fancier later, we can also do `server.on('connection', handler)`. How does that sound?
